# Generated by Django 3.0.3 on 2020-02-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('p_type', models.IntegerField(choices=[(1, 'jar'), (2, 'war')], default=1)),
                ('creator', models.EmailField(max_length=254)),
                ('br', models.CharField(default='master', max_length=20)),
                ('tag', models.CharField(default='v0', max_length=15)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PackageLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=20)),
                ('env', models.IntegerField(choices=[(1, 'online'), (2, 'test'), (3, 'dev')], default=3)),
                ('tag', models.CharField(max_length=15)),
                ('ptime', models.DateTimeField(auto_now_add=True)),
                ('puser', models.EmailField(max_length=254)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectModel')),
            ],
            options={
                'db_table': 'tb_ci_log',
                'managed': True,
            },
        ),
    ]
