# Generated by Django 3.0.3 on 2020-05-02 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20200425_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('p_type', models.CharField(max_length=5)),
                ('creator', models.EmailField(max_length=254)),
                ('br', models.CharField(default='master', max_length=20)),
                ('tag', models.CharField(default='', max_length=15)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_user_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.GroupModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectModel')),
            ],
            options={
                'db_table': 'tb_group_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PackageLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br', models.CharField(max_length=20)),
                ('module', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('env', models.CharField(max_length=12)),
                ('tag', models.IntegerField(blank=True, default=1, null=True)),
                ('msg', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ptime', models.DateTimeField(auto_now_add=True)),
                ('puser', models.EmailField(max_length=254)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectModel')),
            ],
            options={
                'db_table': 'tb_ci_log',
                'ordering': ['-ptime'],
                'managed': True,
                'unique_together': {('project', 'module', 'tag', 'ptime')},
            },
        ),
    ]
