# Generated by Django 3.0.3 on 2020-05-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='func',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
