# Generated by Django 3.0.3 on 2020-04-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_groupprojectmodel_userprojectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelogmodel',
            name='msg',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='tag',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='packagelogmodel',
            unique_together={('project', 'module', 'tag', 'ptime')},
        ),
    ]
