# Generated by Django 3.0.3 on 2020-04-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200419_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagelogmodel',
            options={'managed': True, 'ordering': ['-ptime']},
        ),
    ]
