# Generated by Django 3.0.3 on 2020-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200419_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelogmodel',
            name='tag',
            field=models.IntegerField(default=1),
        ),
    ]
