# Generated by Django 3.0.3 on 2020-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200419_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelogmodel',
            name='env',
            field=models.IntegerField(choices=[(1, 'online'), (2, 'stating'), (3, 'develop')], default=3),
        ),
    ]
