# Generated by Django 3.0.3 on 2020-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200419_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelogmodel',
            name='module',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
