# Generated by Django 3.0.3 on 2020-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200419_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelogmodel',
            name='module',
            field=models.CharField(default='', max_length=20),
        ),
    ]
