# Generated by Django 3.0.3 on 2020-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200419_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelogmodel',
            name='module',
            field=models.CharField(default='ss', max_length=20),
        ),
    ]
