# Generated by Django 3.0.3 on 2020-04-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20200419_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelogmodel',
            name='module',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packagelogmodel',
            name='tag',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
