# Generated by Django 3.0.3 on 2020-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200419_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelogmodel',
            name='msg',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
