# Generated by Django 3.0.3 on 2020-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20200419_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelogmodel',
            name='env',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='p_type',
            field=models.CharField(max_length=5),
        ),
    ]
