# Generated by Django 3.0.3 on 2020-02-19 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20200219_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_ip', models.CharField(db_index=True, max_length=15, unique=True)),
                ('o_ip', models.CharField(max_length=15)),
                ('h_type', models.IntegerField(choices=[(1, 'physical'), (2, 'virtual')], default=1)),
                ('cores', models.IntegerField(blank=True, default=1)),
                ('mem', models.IntegerField(blank=True)),
                ('storage', models.IntegerField(blank=True)),
                ('passwd', models.CharField(blank=True, max_length=50)),
                ('state', models.IntegerField(choices=[(1, 'online'), (2, 'offline')], default=1)),
            ],
            options={
                'db_table': 'tb_host',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserHostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.HostModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_user_host',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupHostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.HostModel')),
                ('t_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.GroupModel')),
            ],
            options={
                'db_table': 'tb_group_host',
                'managed': True,
            },
        ),
    ]
