# Generated by Django 3.0.3 on 2020-05-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(db_index=True, max_length=100, unique=True)),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('scheme', models.CharField(default='test', max_length=10)),
                ('main_class', models.CharField(blank=True, max_length=800, null=True)),
                ('main_args', models.CharField(blank=True, max_length=800, null=True)),
                ('jvm_args', models.CharField(blank=True, max_length=1000, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectModel')),
            ],
            options={
                'db_table': 'tb_app',
                'managed': True,
            },
        ),
    ]
