# Generated by Django 3.0.3 on 2020-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200509_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='script',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
