# Generated by Django 3.0.3 on 2020-05-09 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_applicationmodel_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
