# Generated by Django 3.0.3 on 2020-05-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('application', '0004_applicationmodel_create_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationmodel',
            unique_together={('app', 'module', 'scheme', 'pro_id')},
        ),
    ]
