# Generated by Django 3.0.3 on 2020-05-06 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BUModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bu_name', models.CharField(db_index=True, max_length=100)),
                ('parent_id', models.IntegerField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_bu',
                'managed': True,
            },
        ),
    ]
