# Generated by Django 3.0.3 on 2020-05-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('bu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuApplicationModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.ApplicationModel')),
                ('bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bu.BUModel')),
            ],
            options={
                'db_table': 'tb_bu_app',
                'managed': True,
            },
        ),
    ]
